export { NintentoIcon } from './NintentoIcon'
export { WindowsIcon } from './WindowsIcon'
export { PlaystationIcon } from './PlaystationIcon'
export { SmartphoneIcon } from './SmartphoneIcon'
export { XboxIcon } from './XboxIcon'
